version: '3.8'

services:
  spaceport1:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=spaceport-1

  spaceport2:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=spaceport-2

  spaceport3:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=spaceport-3

  spaceport4:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=spaceport-4

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spaceport1
      - spaceport2
      - spaceport3
      - spaceport4